spring:
  jpa:
    database: mysql
    hibernate.ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:mysql://localhost:3306/data_sync
    username: root
    password: 123456

conf:
  dbType: MYSQL
  hostname: localhost
  port: 3306
  dbName: data_sync
  user: root
  password: 123456
  jobConfTableName: job_conf
  syncConfTableName: sync_conf
  DBConfTableName: db_conf
  fieldMapConfTableName: field_map_conf
  valueFilterConfTableName: value_filter_conf